### ISSUE TITLE
Empty autocomplete list with special characters

### ISSUE THREAD

**Issue by netmonster2** [gliviu/autocomplete-robot-framework#1]
When a keyword contains a special character (like the french ones é è ê à ...) the autocomplete list becomes empty just when that character is typed.

For example, with a keyword "**The é char is here**". When "**The**" is typed (with or without _Ctrl+Space_), the list contains keywords. But just when the "**é**" is typed the list becomes empty although there is a keyword containing the typed string.

**Comment by gliviu** [comment]
That should be fixed now with newly published version.

**Comment by netmonster2** [comment]
Yeah, it's fixed now with the latest version.

Thanks a lot for the fast reaction.
