### ISSUE TITLE
Support for keywords with embedded arguments referenced using libdoc XML file

### ISSUE THREAD

**Issue by Anupal** [gliviu/autocomplete-robot-framework#10]
Hello,
I generated libdoc xml file for my library and pasted it inside fallback libraries directory. The names of keywords with embedded arguments contain `"` which get converted to `&quot;` during libdoc generation. The autocomplete suggests keywords with `&quot;` instead of `"` because of this. Can you please add support to convert html entities to equivalent ascii characters? 

Intended autocomplete: `calculate sum of  "${number_1}" and "${number_2}"`

**XML File**
```
<?xml version="1.0" encoding="UTF-8"?>
<keywordspec name="keywords" type="resource" format="ROBOT" generated="20200228 14:21:07">
<version></version>
<scope></scope>
<namedargs>yes</namedargs>
<doc>Documentation for resource file ``keywords``.</doc>
<kw name="calculate sum of &quot;${number_1}&quot; and &quot;${number_2}&quot;">
<arguments>
</arguments>
<doc>| *Description* | Return the sum of two numbers |
| *Arguments* | number_1, number_2 |
| *Usage* | calculate sum of "${number_1}" and "${number_2}" |
| *Returns* | Integer value as sum |
| *Author* | Name (cec) |</doc>
<tags>
<tag>example</tag>
</tags>
</kw>
</keywordspec>
```

**Comment by gliviu** [comment]
Should be fixed in 3.8.0
