### ISSUE TITLE
Robot Framework 4.0 breaks parameter autocompletion

### ISSUE THREAD

**Issue by ArielDabk** [gliviu/autocomplete-robot-framework#13]
When auto-complete try to show the inside value, this warning shows in the dev tool console:
`TrustedTypes policy dompurify could not be created`

ps. every time i type something this "TrustedTypes" pop up in console again

And it's not auto-completing and literally working... Any advice? 
Windows 10 Pro

ps. Turned off adguard, bitdefender total security (in case if it is)

https://i.imgur.com/TMcCP0T.png

edit1:
RF 4.0

edit2:
Library manager: {
  "BuiltIn": {
    "name": "BuiltIn",
    "status": "success",
    "xmlLibdocPath": "C:\\Users\\dabko\\AppData\\Local\\Temp\\robot-lib-cache\\BuiltIn.xml",
    "sourcePath": "C:\\Users\\dabko\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\robot\\libraries\\BuiltIn.py"
  },
  "Collections": {
    "name": "Collections",
    "status": "success",
    "xmlLibdocPath": "C:\\Users\\dabko\\AppData\\Local\\Temp\\robot-lib-cache\\Collections.xml",
    "sourcePath": "C:\\Users\\dabko\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\robot\\libraries\\Collections.py"
  },
  "DatabaseLibrary": {
    "name": "DatabaseLibrary",
    "status": "success",
    "xmlLibdocPath": "C:\\Users\\dabko\\AppData\\Local\\Temp\\robot-lib-cache\\DatabaseLibrary.xml",
    "sourcePath": "C:\\Users\\dabko\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\DatabaseLibrary\\__init__.py"
  },
  "Browser": {
    "name": "Browser",
    "status": "success",
    "xmlLibdocPath": "C:\\Users\\dabko\\AppData\\Local\\Temp\\robot-lib-cache\\Browser.xml",
    "sourcePath": "C:\\Users\\dabko\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\Browser\\__init__.py"
  }
}

**Comment by gliviu** [comment]
I see that the latest atom (1.55) has this problem. It was working fine
with 1.52.
Until I have some time to investigate I suggest you to downgrade atom to a
previous version.

**Comment by ArielDabk** [comment]
I just downgraded to 1.52, and 1.51 and still the same? 
isn't this is just somehow connected to ver of chromium maybe?

**Comment by gliviu** [comment]
For some reason I can no longer reproduce it.
I downgraded to 1.52 and it works. Moved back to 1.55 and still works although the warning is there.

![TrustedTypes](https://user-images.githubusercontent.com/8597812/112545724-3ad25700-8dc1-11eb-87c5-d4b98d1bb240.gif)

**Comment by ArielDabk** [comment]
you just reproduced it, it should add "default" needed variables and it's not doing it, or you just turned it off from settings?

**Comment by gliviu** [comment]
Ok, you right. Seems there is a problem. I'll take a look.

**Comment by gliviu** [comment]
I can confirm it is caused by recent release of robotframework 4.0. 
Works fine on 3.2.2.
I will try to provide a fix.

**Comment by gliviu** [comment]
Added support for new robotframework version in [rf4](https://github.com/gliviu/autocomplete-robot-framework/tree/rf4) branch.

You can check it using these steps
```bash
apm uninstall autocomplete-robot-framework
git clone git@github.com:gliviu/autocomplete-robot-framework.git
cd autocomplete-robot-framework/
git checkout rf4
apm install
apm link
# Then restart Atom
```

If you see anything wrong please let me know.

Otherwise I'll do a release in a couple of days.
