### ISSUE TITLE
Gherkin support any time soon?

### ISSUE THREAD

**Issue by AeonFX** [gliviu/autocomplete-robot-framework#6]
Unfortunately this package does not support Gherkin notation, which robot-framework does support.
All of my test cases use this notation meaning each test step start with a preposition (AND, WHEN, THEN).
This is breaking the auto-completion unfortunately, thus I always have to delete my prepositions first when I want to check the keyword definition, which is kind of annoying.

Is there any plan to implement Gherkin support for autocompletion?

Ps: this is still the best autocompletion plug-in for robot that I found :-)

**Comment by gliviu** [comment]
Sorry I have no plans to update for Gherkin notation. I'm not using it and it would be quite some work...
I'll support anyone willing to help though.

**Comment by AeonFX** [comment]
I was hoping there might be a "quick" fix by just ignoring the 5 possible gherkin prefixes (and, when, then, but, given) for every keyword. At least this is the way it's implemented in robot, as it can be seen here https://github.com/robotframework/robotframework/blob/f177822d7b10b59ec25ca1086b861564df58326d/src/robot/running/namespace.py#L293    Maybe this helps anyone. Unfortunately I am not a python dev and cannot tell if anything like that can be implemented with the autocomplete-plus API.

**Comment by gliviu** [comment]
That's a good hint. I'll take a look this weekend.

**Comment by gliviu** [comment]
Until I publish the new version you can try it following these steps.
1. close Atom
2. open command prompt in some empty dir
```bash
git clone https://github.com/gliviu/hyperclick-robot-framework
cd hyperclick-robot-framework/
git checkout bdd
apm uninstall hyperclick-robot-framework
apm install
cd ..
git clone https://github.com/gliviu/autocomplete-robot-framework
cd autocomplete-robot-framework/
git checkout bdd
apm uninstall autocomplete-robot-framework
apm install
apm link
apm list
```
3. check the output from ```apm list```. it should contain something like
```
autocomplete-robot-framework@3.4.0-bdd
hyperclick-robot-framework@1.7.0-bdd
```
note the ```bdd``` at the end of each version.

4. open Atom

Now bdd style tests should work in both hyperclick and autocomplete packages.

**Comment by AeonFX** [comment]
Perfect! Everything runs smooth now with hyperclick, autocorrect and BDD test cases.
Also thanks for the quick workaround with apm, however I think there is one apm link missing after the hyperclick install.

**Comment by gliviu** [comment]
Yes indeed. I'll publish soon so there will be no apm tricks needed. Don't forget to uninstall the test versions before getting the official release.
